---
title: "Stationarity test"
output: html_notebook
---

## Preamble

```{r message=FALSE}
library(DBI)
library(RSQLite)
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
```

## Load all data

```{r}
load_table <- function(tbl_name) {
  db <- dbConnect(SQLite(), 'db.sqlite')
  tbl <- dbGetQuery(db, str_glue('SELECT * FROM {tbl_name}'))
  dbDisconnect(db)
  
  tbl
}
```


```{r}
output <- load_table('output')
runs <- load_table('runs')
output_runs <- output %>% left_join(runs, 'run_id')
```

## Test one run

```{r}
output1 <- output %>% filter(run_id == 64)
```

```{r}
ggplot(output1, aes(x = time, y = beta_500)) +
  geom_line()
```

```{r}
ggplot(output1, aes(x = time, y = H)) +
  geom_line()
```


## Just plot 'em all

```{r}
if(!dir.exists('plots')) {
  dir.create('plots')
}
for(beta in sort(unique(output_runs$beta_init_mean))) {
  for(prod_func in c('A', 'AF')) {
    subdir <- file.path('plots', prod_func, sprintf('beta=%.3f', beta))
    if(!dir.exists(subdir)) {
      dir.create(subdir, recursive = TRUE)
    }
    
    LxL <- 200 * 200
    
    df <- output_runs %>%
      filter(productivity_function_FH == sprintf('FH_%s', prod_func) & beta_init_mean == beta) %>%
      select(time, max_rate_FH, rate_DF, H, A, F) %>%
      mutate(H = H / LxL, A = A / LxL, F = F / LxL) %>%
      mutate(D = 1 - H - A - F) %>%
      gather(`H`, `A`, `F`, `D`, key = 'state', value = 'density')
    
    p <- ggplot(df, aes(x = time, y = density, color = state)) +
      geom_line() +
      facet_grid(rows = vars(max_rate_FH), cols = vars(rate_DF), labeller = labeller(.rows = label_both, .cols = label_both))
    ggsave(file.path(subdir, 'e1-H_over_time.pdf'), p, width = 15, height = 15)
  }
}
```

